export const GET_SOMTHING = 'GET_SOMTHING';
export const GET_SOMTHING_PENDING = 'GET_SOMTHING_PENDING';
export const GET_SOMTHING_FULFILLED = 'GET_SOMTHING_FULFILLED';
export const GET_SOMTHING_REJECTED = 'GET_SOMTHING_REJECTED';
//export const GET_SOMTHING = 'GET_SOMTHING';
